[[CURRENCIES]]
code="RESONANCE"
issuer="GBC7L42E7ZKCXCCNGRLQUGPCFHQIFVGLYR7N5EMHIBS66ZFDHC6UYX72"
display_decimals=8
name="Harmonic Resonance"
desc="Harmonic Resonance (RESONANCE) is the primary reward and utility token for engagement and progression. Pioneers earn RESONANCE by resonating with geo-anchored Nodes. RESONANCE is spent on enhancing personal experience, status, and influence."
conditions="The total supply is fixed at 314,159,265 RESONANCE, tied thematically to the digits of Pi, reinforcing the core lore of the game. RESONANCE emission is subject to programmatic scarcity via the Harmonic Awakening halving schedule."
image="https://www.harmonicrealm.app/resonance_icon.png"
fixed_number=314159265